version: '3'

services:
  node-app:
    restart: always
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/social-survey-app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    restart: always
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    command: [--auth]
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge